# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FG0Bbndie_tbxSy2Xp-TQRmqR-1OZD6
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


# ---------------------------------------------------------
# 1. Load Auto MPG Dataset
# ---------------------------------------------------------

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"

column_names = [
    "mpg",
    "cylinders",
    "displacement",
    "horsepower",
    "weight",
    "acceleration",
    "model_year",
    "origin",
    "car_name"
]

data = pd.read_csv(
    url,
    names=column_names,
    na_values="?",
    comment="\t",
    sep=r"\s+",
    skipinitialspace=True
)

print("Dataset loaded successfully.")
print("Dataset shape:", data.shape)


# ---------------------------------------------------------
# 2. Data Preprocessing
# ---------------------------------------------------------

data["horsepower"] = pd.to_numeric(
    data["horsepower"],
    errors="coerce"
)

data = data.dropna()

print("\nAfter preprocessing:")
print("Dataset shape:", data.shape)


# ---------------------------------------------------------
# 3. Define Features and Target
# ---------------------------------------------------------

features = [
    "cylinders",
    "displacement",
    "horsepower",
    "weight",
    "acceleration",
    "model_year",
    "origin"
]

X = data[features]
y = data["mpg"]


# ---------------------------------------------------------
# 4. Train-Test Split
# ---------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)


# ---------------------------------------------------------
# 5. Multiple Linear Regression
# ---------------------------------------------------------

linear_model = Pipeline([
    ("scaler", StandardScaler()),
    ("regressor", LinearRegression())
])

linear_model.fit(X_train, y_train)

y_pred_linear = linear_model.predict(X_test)

mae_linear = mean_absolute_error(y_test, y_pred_linear)
mse_linear = mean_squared_error(y_test, y_pred_linear)
rmse_linear = np.sqrt(mse_linear)
r2_linear = r2_score(y_test, y_pred_linear)

print("\n----- Multiple Linear Regression -----")
print("MAE  :", mae_linear)
print("MSE  :", mse_linear)
print("RMSE :", rmse_linear)
print("R2   :", r2_linear)


# ---------------------------------------------------------
# 6. Polynomial Regression
# ---------------------------------------------------------

polynomial_model = Pipeline([
    ("poly", PolynomialFeatures(degree=2, include_bias=False)),
    ("scaler", StandardScaler()),
    ("regressor", LinearRegression())
])

polynomial_model.fit(X_train, y_train)

y_pred_poly = polynomial_model.predict(X_test)

mae_poly = mean_absolute_error(y_test, y_pred_poly)
mse_poly = mean_squared_error(y_test, y_pred_poly)
rmse_poly = np.sqrt(mse_poly)
r2_poly = r2_score(y_test, y_pred_poly)

print("\n----- Polynomial Regression -----")
print("MAE  :", mae_poly)
print("MSE  :", mse_poly)
print("RMSE :", rmse_poly)
print("R2   :", r2_poly)


# ---------------------------------------------------------
# 7. Gradient Descent for Linear Regression
# ---------------------------------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

y_train_array = y_train.to_numpy()
y_test_array = y_test.to_numpy()

weights = np.zeros(X_train_scaled.shape[1])
bias = 0.0

learning_rate = 0.01
iterations = 5000

cost_history = []


# Gradient Descent
for i in range(iterations):

    # Prediction
    y_pred = np.dot(X_train_scaled, weights) + bias

    # Error
    error = y_pred - y_train_array

    # Cost
    cost = np.mean(error ** 2) / 2
    cost_history.append(cost)

    # Gradients
    dw = np.dot(X_train_scaled.T, error) / len(X_train_scaled)
    db = np.mean(error)

    # Update parameters
    weights = weights - learning_rate * dw
    bias = bias - learning_rate * db


# ---------------------------------------------------------
# 8. Gradient Descent Prediction
# ---------------------------------------------------------

y_pred_gd = np.dot(X_test_scaled, weights) + bias

mae_gd = mean_absolute_error(y_test_array, y_pred_gd)
mse_gd = mean_squared_error(y_test_array, y_pred_gd)
rmse_gd = np.sqrt(mse_gd)
r2_gd = r2_score(y_test_array, y_pred_gd)

print("\n----- Gradient Descent -----")
print("MAE  :", mae_gd)
print("MSE  :", mse_gd)
print("RMSE :", rmse_gd)
print("R2   :", r2_gd)


# ---------------------------------------------------------
# 9. Model Comparison
# ---------------------------------------------------------

results = pd.DataFrame({
    "Model": [
        "Multiple Linear Regression",
        "Polynomial Regression",
        "Gradient Descent"
    ],
    "MAE": [
        mae_linear,
        mae_poly,
        mae_gd
    ],
    "MSE": [
        mse_linear,
        mse_poly,
        mse_gd
    ],
    "RMSE": [
        rmse_linear,
        rmse_poly,
        rmse_gd
    ],
    "R2 Score": [
        r2_linear,
        r2_poly,
        r2_gd
    ]
})

print("\n===== MODEL COMPARISON =====")
print(results)


# ---------------------------------------------------------
# 10. Actual vs Predicted - Linear Regression
# ---------------------------------------------------------

plt.figure(figsize=(7, 5))

plt.scatter(y_test, y_pred_linear)

plt.xlabel("Actual MPG")
plt.ylabel("Predicted MPG")
plt.title("Actual vs Predicted MPG - Linear Regression")

plt.grid(True)
plt.show()


# ---------------------------------------------------------
# 11. Actual vs Predicted - Polynomial Regression
# ---------------------------------------------------------

plt.figure(figsize=(7, 5))

plt.scatter(y_test, y_pred_poly)

plt.xlabel("Actual MPG")
plt.ylabel("Predicted MPG")
plt.title("Actual vs Predicted MPG - Polynomial Regression")

plt.grid(True)
plt.show()


# ---------------------------------------------------------
# 12. Gradient Descent Convergence
# ---------------------------------------------------------

plt.figure(figsize=(7, 5))

plt.plot(cost_history)

plt.xlabel("Iterations")
plt.ylabel("Cost")
plt.title("Gradient Descent Convergence")

plt.grid(True)
plt.show()


# ---------------------------------------------------------
# 13. Model Performance Comparison
# ---------------------------------------------------------

results.set_index("Model")[["MAE", "RMSE"]].plot(
    kind="bar",
    figsize=(8, 5)
)

plt.ylabel("Error")
plt.title("Regression Model Error Comparison")

plt.xticks(rotation=15)

plt.grid(axis="y")
plt.show()